INSERT INTO users (name, email, password) VALUES ('Sascha', 'sascha@sascha.com', '123');
INSERT INTO users (name, email, password) VALUES ('Jesse', 'jesse@jesse.com', '123');
INSERT INTO users (name, email, password) VALUES ('Mark', 'mark@mark.com', '123');
INSERT INTO users (name, email, password) VALUES ('Elliot Dickinson', 'derrick_pollich@gmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Lloyd Boehm', 'ebba.deckow@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Erna Cassin', 'miguel.barrows@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Edison Brown', 'alysha.daniel@boyer.tv', 'password');
INSERT INTO users (name, email, password) VALUES ('Lionel Morar', 'bradtke.mallie@yahoo.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Donnie Lueilwitz', 'kattie_dibbert@winnifred.name', 'password');
INSERT INTO users (name, email, password) VALUES ('Obie Howell', 'elisha_wisoky@gmail.com', 'password');
