INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (1, 'star wars', 1, 12);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (2, 'lord of the rings', 1, 12);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (3, 'harry potter', 1, 12);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (4, 'the lies of locke lamora', 5, 11);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (1, 'sherlock holmes', 1, 12);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (2, 'star trek TNG', 3, 5);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (3, 'the mandalorian', 2, 7);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (4, 'stormbringer trilogy', 1, 10);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (1, 'the first law trilogy', 6, 12);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (2, 'bananas in pyjamas', 1, 8);
INSERT INTO timelines (user_id, name, start_month, end_month) VALUES (1, 'COVID-19 (2020)', 1, 12);
