INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'WHO Announces Mysterious Coronavirus-Related Pneumonia in Wuhan, China', 'At this point, the World Health Organization (WHO) still has doubts about the roots of what would become the COVID-19 pandemic, noting that the spate of pneumonia-like cases in Wuhan could have stemmed from a new coronavirus. There are 59 cases so far, and travel precautions are already at the forefront of experts’ concerns.', 'January', 9);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'CDC Says 3 US Airports Will Begin Screening for Coronavirus', 'Three additional cases of what is now the 2019 novel coronavirus are reported in Thailand and Japan, causing the CDC to begin screenings at JFK International, San Francisco International, and Los Angeles International airports. These airports are picked because flights between Wuhan and the United States bring most passengers through them.', 'January', 20);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'WHO Issues Global Health Emergency', 'With a worldwide death toll of more than 200 and an exponential jump to more than 9800 cases, the WHO finally declares a public health emergency, for just the sixth time. Human-to-human transmission is quickly spreading and can now be found in the United States, Germany, Japan, Vietnam, and Taiwan.', 'January', 31);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Global Air Travel Is Restricted', 'By 5 pm on Sunday, those en route to the United States have to have left China or they can face a 2-week home-based quarantine if they had been in Hubei province. Mainland visitors, however, will need to undergo health screenings upon their return, and foreign nationals can even be denied admittance. Other countries beginning to impose similar air-travel restrictions at this point include Australia, Germany, Italy, and New Zealand.', 'February', 2);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'China’s COVID-19 Deaths Exceed Those of SARS Crisis', 'The COVID-19 death toll surpasses that of the severe acute respiratory syndrome (SARS) outbreak from 17 years ago, totaling 908 reported deaths in China in the last month compared with 774 deaths in the SARS crisis.', 'February', 10);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'CDC Says COVID-19 Is Heading Toward Pandemic Status', 'Explaining what would signify a pandemic, Nancy Messonnier, MD, director of the CDCs National Center for Immunization and Respiratory Diseases, says that thus far COVID-19 meets 2 of the 3 required factors: illness resulting in death and sustained person-to-person spread. Worldwide spread is the third criteria not yet met at the time.', 'February', 25);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, '21 Passengers on California Cruise Ship Test Positive', 'Twenty-one people of just 46 tested aboard a cruise ship carrying more than 3500 people off the California coast test positive for COVID-19, with 19 being crew members. The ship is held at sea instead of being allowed to dock in San Francisco while testing is conducted. Since the event, 60 passengers have sued the cruise line and parent company, Carnival Corp, for gross negligence in how passenger safety was handled.', 'March', 6);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'CMS Temporarily Expands Use of Telehealth', 'CMS expands its telehealth rules, permitting use during the COVID-19 pandemic as a means to protect older patients from potential exposure. The relaxation allows Medicare to cover telehealth visits the same as it would regular in-person visits.', 'March', 17);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Trump Signs CARES Act Into Law', 'The House of Representatives approves the CARES act, the largest economic recovery package in history, and Trump signs it into law. The bipartisan legislation provides direct payments to Americans and expansions in unemployment insurance.', 'March', 27);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Troubles With the COVID-19 Cocktail', '“What do you have to lose?” Trump asks when touting the malaria drug hydroxychloroquine or the related chloroquine as possible treatments for COVID-19. With a common antibiotic, azithromycin, the drug cocktail becomes an early candidate to prevent hospitalization or death. But Trump’s promotion of the combination, despite known heart risks for some patients, prompts the American Heart Association, the American College of Cardiology, and the Heart Rhythm Society to warn in a joint guidance that the drugs are not for everyone.', 'April', 8);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, '“Gating Criteria” Emerge as a Way to Reopen the Economy', 'After Trump briefly entertains the idea of reopening the US economy in time for Easter Sunday, the White House releases broad guidelines for how people could return to work, to church, and to restaurants and other venues. The plan outlines the concept of “gating criteria,” which call for states or metropolitan areas to achieve benchmarks in reducing COVID-19 cases or deaths before taking the next step toward reopening.', 'April', 16);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Young, Poor Avoid Care for COVID-19 Symptoms', 'As the pandemic lingers, the term “deferred care” caught fire in health care circles—referring to the fact that many would avoid a doctor’s office or hospital for any procedure that could wait. But a Gallup poll finds a darker side to this phenomenon: 1 in 7 Americans report they would not seek care for a fever or dry cough—the classic symptoms of COVID-19. The reason? Cost concerns. Those most likely to avoid medical treatment for symptoms are younger than age 30 and make less than $40,000 a year. By the end of April, 26.5 million Americans have filed for unemployment since mid-March.', 'April', 28);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Saliva-Based Diagnostic Test Allowed for At-Home Use', 'The FDA broadens authorization of a saliva-based test to detect COVID-19 infection; the EUA is granted to Rutgers Clinical Genomics Laboratory. The test makes it possible for those who cannot get to a collection center to get tested, including those who are home because they are ill, quarantined, or at high risk of infection due to their age or comorbidities.', 'May', 9);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'United States and AstraZeneca Form Vaccine Deal', 'The Trump administration and AstraZeneca announce a collaboration to speed development of a COVID-19 vaccine called AZD1222. HHS says it expects the first doses to be available as early as October 2020; phase 3 clinical studies are underway this summer.', 'May', 21);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'US COVID-19 Deaths Pass the 100,000 Mark', 'The CDC says surpassing 100,000 deaths is a “sobering development and a heart-breaking reminder of the horrible toll of this unprecedented pandemic.” It asks that Americans continue following local and state guidance on prevention strategies, such as social distancing, good hand hygiene, and wearing a face mask while in public.', 'May', 28);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'US COVID-19 Cases Reach 2 Million', 'The number of confirmed cases of COVID-19 hits 2 million in the United States as new infections continue to rise in 20 states. Cases begin to spike as states ease social distancing restrictions.', 'June', 10);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'WHO Ends Study Into Hydroxychloroquine', 'WHO announces it will stop testing hydroxychloroquine as a treatment for COVID-19. The data from the Solidarity Trial show the drug did not reduce mortality. According to WHO, patients who were previously administered the drug would finish their course or stop based on a supervisor’s discretion.', 'June', 18);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Fauci Warns New COVID-19 Cases Could Hit 100,000 a Day', 'In his appearance before the Senate Health, Education, Labor, and Pensions Committee, Fauci warns that while the current daily number of new cases in the United States is hovering around 40,000, that could reach as high as 100,000 new cases per day given the outbreak’s current trajectory.', 'June', 30);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'CMS Plans to Pay More for Home Dialysis Equipment', 'CMS proposes a rule aimed at keeping patients outside of dialysis centers for treatment as the nation faces rising cases. The transitional add-on payment for new and innovative equipment or supplies would allow greater access to home dialysis machines, improving accessibility for Medicare beneficiaries.', 'July', 7);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Early Moderna Data Point to Vaccine Candidate’s Efficacy', 'Data from phase 1/2 trials of Moderna Inc’s COVID-19 vaccine show that doses produced immune responses in all 3 groups of 15 volunteers. The company was the first to enter large-scale human trials. Adverse effects of the vaccine candidate, which is administered twice 28 days apart, include injection site pain and chills.', 'July', 14);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'HHS, DOD Announce Vaccine Distribution Agreement With Pfizer and BioNTech', 'HHS and the Department of Defense (DOD) strike a partnership with biotech giants Pfizer and BioNTech for a December delivery of 100 million doses of their COVID-19 vaccine candidate, BNT162, in a deal that could expand to 600 million doses if the vaccine receives approval or an EUA from the FDA, and even then only if phase 3 clinical trial results confirm that the vaccine is safe and effective.', 'July', 22);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'New US Pandemic Phase; US to Pay Sanofi, GlaxoSmithKline $2B for Vaccine', 'Coronavirus response coordinator Deborah Birx, MD, says the United States has entered a new phase of the pandemic, as widespread cases nationwide differ from early concentrated outbreaks first reported in March and April. Birx’s comments come as the United States agrees to a $2.1 billion deal with GlaxoSmithKline and Sanofi Pasteur in an effort to develop, manufacture, and scale up delivery of a COVID-19 vaccine.', 'August', 3);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Severe Obesity Increases Mortality Risk From COVID-19', 'Investigators from Kaiser Permanente publish their findings showing that patients with a body mass index (BMI) of 40 to 44 kg/m2 have a risk of death from COVID-19 that is more than twice that of individuals whose BMI is 18.5 to 24 mg/m2. An abundance of comprehensive patient data enabled the team to isolate obesity’s effects compared with those resulting from more than 20 comorbidities, health care use, and population density, among others. At the heart of this finding is that excess fat exacerbates the breathing issues brought on by COVID-19.', 'August', 12);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Remdesivir’s Clinical Benefits Questioned', 'A global, multicenter study finds that the antiviral drug remdesivir had little effect on patients hospitalized with COVID-19. The findings, published in JAMA, indicate there were no significant differences in duration of supplemental oxygen or hospitalization between the intervention group given remdesivir and the control group given standard care.', 'August', 24);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Bioethicists Weigh In on Equitable Vaccine Distribution', 'ineteen bioethicists outline measures for equitable distribution of limited supplies of any COVID-19 vaccine; the plan, called the Fair Priority Model, considers 3 types of harms caused by COVID-19 and 3 values that must be adhered to when considering the allocation of a scarce supply of vaccine.', 'September', 3);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Pfizer, BioNTech Expand Phase 3 Trial', 'After initially aiming to recruit 30,000 participants, Pfizer and BioNTech announce they will expand the phase 3 trial of their COVID-19 vaccine by 50% to 44,000. The goal of expanding the trial is to increase data on safety and efficacy and promote a more diverse population, including adolescents as young as 16 years and patients with HIV, hepatitis C, or hepatitis B. The Pfizer/BioNTech vaccine is provided as 2 shots given 3 weeks apart, but the vaccine must be kept at a temperature of –70 degrees Celsius (–94 degrees Fahrenheit), which may make distribution a challenge.', 'September', 14);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Johnson & Johnson Begins Phase 3 Vaccine Trial', 'Johnson & Johnson announces that it began a large phase 3 clinical trial of its COVID-19 vaccine candidate. This vaccine does not need to be frozen and may require 1 administration instead of 2. The trial is expected to test the vaccine in 60,000 participants, making it the largest phase 3 trial of all vaccines currently being tested.', 'September', 21);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Trump, First Lady Test Positive for COVID-19; Trump Enters Hospital', 'President Trump announces that he and First Lady Melania Trump have tested positive for COVID-19. After experiencing mild symptoms of the disease, Trump was taken to Walter Reed National Military Medical Center, “out of an abundance of caution,” said Press Secretary Kayleigh McEnany in a statement.', 'October', 2);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Global Cases Top 40 Million', 'Data from Johns Hopkins University indicate that COVID-19 cases have topped 40 million worldwide as the United States and other countries see their highest rates of new cases in months. More than 1.1 million people have been killed by the virus worldwide so far, and nearly 220,000 of those deaths were in the United States, which remains the hardest-hit country in the world.', 'October', 19);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'CMS Issues Vaccine, Treatment Coverage Rules', 'CMS provides new rules for insurance coverage, increasing what Medicare pays hospitals for COVID-19 treatments. Trump and Congress had enacted legislation calling for COVID-19 vaccines to be free, but new rules were necessary to fit that policy into the various payment requirements for public and private insurance. The new rules waive co-pays or deductibles on vaccines for seniors with Medicare.', 'October', 28);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'US Reports Unprecedented 100,000 Cases in 1 Day', 'The US hits a grim milestone with 100,000 new COVID-19 cases reported in a single day for the first time. The unprecedented spike in cases leads to a shortage of N95 face masks at health care facilities despite increased production, and workers continue to ration and reuse masks with no end in sight.', 'November', 4);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Indoor Venues Responsible for Much of COVID-19’s Spread', 'A new study in Nature observes that most new cases of COVID-19 originated from indoor gatherings in places like restaurants, gyms, and grocery stores, according to analysis of cell phone mobility data from large cities. The authors suggest that low-income neighborhoods have higher new case burdens because their public venues are more crowded and residents are more likely to work outside their homes.', 'November', 11);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'Pfizer, BioNTech Vaccine Is 95% Effective', 'The results of a nearly 44,000-person trial demonstrate that the COVID-19 vaccine from Pfizer and BioNTech is 95% effective, making it as effective as vaccines for shingles and measles. Pfizer also announces that it will seek FDA approval within days so that distribution of the vaccine can happen by the end of the year.', 'November', 18);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'FDA Advisory Panel Recommends Pfizer, BioNTech COVID-19 Vaccine', 'The results of a nearly 44,000-person trial demonstrate that the COVID-19 vaccine from Pfizer and BioNTech is 95% effective, making it as effective as vaccines for shingles and measles. Pfizer also announces that it will seek FDA approval within days so that distribution of the vaccine can happen by the end of the year.', 'December', 10);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'New COVID-19 Variant Circling the UK', 'The UK announces that a new strain of the virus that causes COVID-19, B.1.1.7, is spreading across the country. The novel variant is more contagious, but does not appear to be more lethal or lead to more severe disease.', 'December', 21);
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day) VALUES (4, 5, 'First US Case of New COVID-19 Variant Found in Colorado', 'The recently discovered novel variant found a week prior in the United Kingdom is detected in a Colorado man in his 20s with no travel history. Scientists say they are concerned, but not surprised, since viruses are known to mutate.', 'December', 29);

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Lotide', 'Today we started our first project, Lotide! Lotide is a clone of the Lodash JavaScript library.', 'April', 26, 'https://d.pr/i/GCeLfa+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Mock Programming Test', 'Today we completed our first Fundamental Friday which included our first programming test.', 'April', 30, 'https://www.personality-and-aptitude-career-tests.com/images/programmer.gif');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Submit Lotide', 'Its finally time to submit Lotide in compass!', 'May', 3, 'https://www.personality-and-aptitude-career-tests.com/images/programmer.gif');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'TinyApp', 'Today we will start the our next project, TinyApp. TinyApp is a URL shortening service similar to TInyURL, Bitly, or Goo.gl', 'May', 10, 'https://d.pr/i/1bi2X/2bN5EotL+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Submit TinyApp', 'Its finally time to submit TinyApp in compass!', 'May', 13, 'https://d.pr/i/1bi2X/2bN5EotL+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Tweeter', 'A single page app (SPA) built with HTML, CSS, JS, jQuery and AJAX.', 'May', 17, 'https://d.pr/i/nxGKF0+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Submit Tweeter', 'Its finally time to submit Tweeter in compass!', 'May', 20, 'https://d.pr/i/nxGKF0+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Midterm Project', 'You and your team will have 5 days to build a full stack web app for a client of your choice.', 'May', 28, 'https://d.pr/i/pZcRYt+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Present Midterm Project', 'Today you will present your midterm to the rest of the cohort and submit your work for evaluation.', 'June', 3, 'https://d.pr/i/pZcRYt+');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Scheduler', 'Using the latest tools and techniques, we build and test a React application that allows users to book and cancel interviews. We combine conside API with a WebSocket server to build a realtime experience.', 'June', 7, 'https://s3-us-west-2.amazonaws.com/reactv2/figures/00887645-020b-4f58-b0f1-72ebce67ac2f.png');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Submit Scheduler', 'Today we will finally submit our Scheduler project!', 'June', 16, 'https://s3-us-west-2.amazonaws.com/reactv2/figures/00887645-020b-4f58-b0f1-72ebce67ac2f.png');

INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Final Project', 'You will have two weeks to work with your cohort-mates to build an application from the ground up. Your group will decice what the application does and which technologies you will use.', 'July', 2, 'https://d.pr/i/JTIygV+');
INSERT INTO instances (timeline_id, instance_colour_id, name, description, month, day, image) VALUES (5, 1, 'Presentation Day', 'Today is the big day! Today we present our final projects.', 'July', 15, 'https://d.pr/i/JTIygV+');